#!/usr/bin/env bash

set -euo pipefail

echo "This public repo is generated by the internal release tooling."
echo "Update versions from the internal xweather-mapsgl-apple repo and re-render the public release artifacts."
